"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fail_1 = require("./fail");
const isFail_1 = require("./isFail");
const isOK_1 = require("./isOK");
const isOkFail_1 = require("./isOkFail");
const ok_1 = require("./ok");
const okFail_1 = require("./okFail");
const okFetch_1 = require("./okFetch");
const okPromise_1 = require("./okPromise");
exports.default = Object.assign(Object.assign(Object.assign(Object.assign(Object.assign(Object.assign(Object.assign(Object.assign({}, fail_1.default), isFail_1.default), isOK_1.default), isOkFail_1.default), ok_1.default), okFail_1.default), okFetch_1.default), okPromise_1.default);
